export * from './paciente.service'
export * from './medico.service'
export * from './registro.service'
export * from './receta.service'
export * from './documento.service'
export * from './resumen.service'
export * from './vinculacion.service'
export * from './tracking.service'
